/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:a6abec62-f087-4408-868f-aae2fc65909d",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_cZqPtz2UV",
    "aws_user_pools_web_client_id": "7jg35roqqrh1k90e7i0f239q22",
    "oauth": {}
};


export default awsmobile;
